import team from './page/team'
import sponsor from './page/sponsor'
import achievement from './page/achievement'
import misc from './page/misc'
import home from './page/home'
import about from './page/about'
import map from './page/map'
import team_desc from './page/team_desc'
import team_leads from './page/team_leads'
import crowdfunding from './page/crowdfunding'
import achievement_stats from './page/achievement_stats'
import supporters from './page/supporters'
import sponsorship from './page/sponsorship'
import gallery from './page/gallery'
export const schemaTypes = [sponsor, team, achievement, misc, home, about, map, team_desc, team_leads, crowdfunding, achievement_stats, supporters, sponsorship, gallery]
